version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - '80:80'
        networks:
            - frontend
            - backend

    redis:
        image: redis:latest
        container_name: redis
        networks:
            - backend
        depends_on:
            - nginx

    python_app:
        build:
            context: ./python_app
        container_name: python_app
        networks:
            - backend
        depends_on:
            - redis

    mongodb1:
        image: mongo:latest
        container_name: mongodb1
        volumes:
            - mongo_data1:/data/db
        networks:
            - backend
        depends_on:
            - python_app

    mongodb2:
        image: mongo:latest
        container_name: mongodb2
        volumes:
            - mongo_data2:/data/db
        networks:
            - backend
        depends_on:
            - python_app

volumes:
    mongo_data1:
    mongo_data2:

networks:
    frontend:
    backend:
